homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret lat_home
  longitude: !secret long_home
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 57
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret time_zone
  # Customization file
  customize: !include customize.yaml

zone:
  - name: Home
    latitude: !secret lat_home
    longitude: !secret long_home
    radius: 50
    icon: mdi:home
  - name: Work
    latitude: !secret lat_work
    longitude: !secret long_work
    icon: mdi:briefcase

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
#  api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
   reporting: false

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:
  exclude:
    domains:
      - automation
      - sun
    entities:
      - sensor.current_version
      - sensor.ha_upstream
      - sensor.owm_cloud_coverage
      - sensor.owm_condition
      - sensor.owm_humidity
      - sensor.owm_temperature
      - sensor.owm_wind_speed
      - sensor.waze_travel_time

# Configure saving of history data
recorder:
  purge_keep_days: 5

  exclude:
    domains:
      - automation
      - sun
    entities:
      - sensor.current_version
      - sensor.ha_upstream
      - sensor.owm_cloud_coverage
      - sensor.owm_condition
      - sensor.owm_humidity
      - sensor.owm_temperature
      - sensor.owm_wind_speed
      - sensor.waze_travel_time
      - sensor.time_utc

# Reduce SD card wear
logger:
  default: error

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

binary_sensor:
  # Flic bluetooth buttons
  - platform: flic
  # Bayesian sensor for presence
  - platform: bayesian
    name: my_presence
    prior: 0.5
    probability_threshold: 0.9
    observations:
      - entity_id: !secret my_phone_life360
        prob_given_true: 0.9
        prob_given_false: 0.4
        platform: 'state'
        to_state: 'home'
      - entity_id: !secret my_phone_nmap
        prob_given_true: 0.9
        prob_given_false: 0.1
        platform: 'state'
        to_state: 'home'
  - platform: uptimerobot
    api_key: !secret key_uptime
  - platform: wyzesense
    device: "/dev/hidraw0"

# Sensors
sensor:
  # Pi CPU Temperature
  - platform: command_line
    name: CPU Temperature
    command: "cat /sys/class/thermal/thermal_zone0/temp"
    unit_of_measurement: "°C"
    value_template: '{{ value | multiply(0.001) | round(1) }}'
  # Crime reports within 2 miles of Home
  - platform: crimereports
    name: crimereports
    radius: 3218
  # Weather - open weather map
  - platform: openweathermap
    api_key: !secret key_owm
    monitored_conditions:
      - weather
      - temperature
      - wind_speed
      - humidity
      - clouds
  # Waze travel time from Home to Work
  - platform: waze_travel_time
    origin: !secret address_home
    destination: !secret address_work
    region: 'US'
    incl_filter: !secret waze_include
    excl_filter: !secret waze_exclude
  # Desktop hardware monitor - cpu temp
  - platform: rest
    name: Desktop CPU temp
    resource: !secret ip_desktop
    value_template: >-
      {% for state in value_json -%}
        {% if state.SensorName == "CPU Package" and state.SensorClass == "CPU [#0]: Intel Core i7-4790K: DTS" %}
          {{ state.SensorValue }}
        {% endif %}
      {%- endfor -%}
  # Desktop hardware monitor - gpu temp
  - platform: rest
    name: Desktop GPU temp
    resource: !secret ip_desktop
    value_template: >-
      {% for state in value_json -%}
        {% if state.SensorName == "GPU Temperature" %}
          {{ state.SensorValue }}
        {% endif %}
      {%- endfor -%}
  # Home Assistant update checker
  - platform: rest
    resource: https://pypi.python.org/pypi/homeassistant/json
    name: HA upstream
    value_template: '{{ value_json.info.version }}'
    scan_interval: 3600
  # Current home assistant version
  - platform: version
  # Xiaomi humidity and temp sensors
  - platform: mitemp_bt
    name: Basement Sensor
    mac: !secret mac_sensor_xiaomi_basement
    median: 3
    adapter: hci1
    monitored_conditions:
      - temperature
      - humidity
      - battery
  - platform: mitemp_bt
    name: Bedroom Sensor
    mac: !secret mac_sensor_xiaomi_bedroom
    median: 3
    adapter: hci1
    monitored_conditions:
      - temperature
      - humidity
      - battery
  - platform: time_date
    display_options:
      - 'time_utc'

# Text to speech
tts:
  - platform: google_translate

# Enable Alexa
alexa:

# Cloud
# Configure sensors available to Alexa
cloud:
  alexa:
    filter:
      include_entities:
        - sensor.basement_sensor_humidity
        - sensor.basement_sensor_temperature
        - sensor.waze_travel_time
      include_domains:
        - sensor
    entity_config:
      sensor.basement_sensor_humidity:
        name: Basement humidity
        description: Basement humidity sensor
      sensor.basement_sensor_temperature:
        name: Basement temperature
        description: Basement temperature sensor
      sensor.waze_travel_time:
        name: Work travel time
        description: Waze travel time to work

device_tracker:
  # Network devices
  - platform: nmap_tracker
    hosts: 192.168.1.0/24
    new_device_defaults:
      track_new_devices: False

# Enable Telegram notifier
notify:
  - platform: telegram
    name: telegram
    chat_id: !secret telegram_chat_me

# Connect to Telegram chat bot
telegram_bot:
  - platform: polling
    api_key: !secret telegram_key
    allowed_chat_ids:
      - !secret telegram_chat_me

# Life360 device tracker
life360:
  max_gps_accuracy: 200

wemo:
  static:
    - !secret ip_wemo

# Shell commands
# TODO: figure out why blink1-tool not executing without full path
shell_command:
  # Blink1 flash red
  blink1_flash_red: /home/pi/bin/blink1-tool --red --blink 5
  # Blink1 steady red
  blink1_red: /home/pi/bin/blink1-tool --red
  # Blink1 off
  blink1_off: /home/pi/bin/blink1-tool --off

mqtt:
  broker: !secret mqtt_server
  port: !secret mqtt_port
  username: !secret mqtt_user
  password: !secret mqtt_pass
  will_message:
    topic: 'home-assistant/lwt'
    payload: 'OFFLINE'

# Home Assistant Community Store component
hacs:
  token: !secret hacs_token

group: !include groups.yaml
automation: !include_dir_merge_list automations
script: !include scripts.yaml
