# Turn bedroom lights on 100% when Flic button single pressed
- alias: Flic bedroom lights on
  initial_state: on
  trigger:
  - event_data:
      button_name: !secret flic_bedroom
      click_type: single
    event_type: flic_click
    platform: event
  condition: []
  action:
  - data:
      entity_id: light.bedroom
      brightness_pct: 100
    service: light.turn_on
# Turn bedroom lights off when Flic button long pressed
- alias: Flic bedroom lights off
  initial_state: on
  trigger:
  - event_data:
      button_name: !secret flic_bedroom
      click_type: hold
    event_type: flic_click
    platform: event
  condition: []
  action:
  - data:
      entity_id: light.bedroom
    service: light.turn_off
# Turn bedroom lights down when Flic button double pressed
- alias: Flic bedroom nightlight
  initial_state: on
  trigger:
  - event_data:
      button_name: !secret flic_bedroom
      click_type: double
    event_type: flic_click
    platform: event
  condition: []
  action:
  - data:
      entity_id: light.desk, light.wall
    service: light.turn_off
  - data:
      entity_id: light.ceiling
      brightness_pct: 1
    service: light.turn_on
# Turn on porch light when arriving home if sun down
- alias: Porch light on
  initial_state: on
  trigger:
    platform: state
    entity_id: !secret dan_phone_owntracks
    to: 'home'
  condition:
    condition: sun
    after: sunset
  action:
    - data:
        entity_id: light.porch
      service: light.turn_on
    # temp - for debug
    - data:
        message: "Porch light turned on"
      service: notify.hangouts
