# Turn bedroom lights on 100% when Flic button single pressed
- alias: Flic bedroom lights on
  initial_state: on
  trigger:
  - event_data:
      button_name: !secret flic_bedroom
      click_type: single
    event_type: flic_click
    platform: event
  condition: []
  action:
  - data:
      entity_id: light.bedroom
      brightness_pct: 100
    service: light.turn_on
# Turn bedroom lights off when Flic button long pressed
- alias: Flic bedroom lights off
  initial_state: on
  trigger:
  - event_data:
      button_name: !secret flic_bedroom
      click_type: hold
    event_type: flic_click
    platform: event
  condition: []
  action:
  - data:
      entity_id: light.bedroom
    service: light.turn_off
# Turn bedroom lights down when Flic button double pressed
- alias: Flic bedroom nightlight
  initial_state: on
  trigger:
  - event_data:
      button_name: !secret flic_bedroom
      click_type: double
    event_type: flic_click
    platform: event
  condition: []
  action:
  - data:
      entity_id: light.desk, light.wall
    service: light.turn_off
  - data:
      entity_id: light.ceiling
      brightness_pct: 1
    service: light.turn_on
# Turn on porch light when arriving home if sun down
- alias: Porch light on
  initial_state: on
  trigger:
    platform: state
    entity_id: binary_sensor.my_presence
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: 'sun.sun'
        state: 'below_horizon'
      - condition: state
        entity_id: 'light.porch'
        state: 'off'
  action:
  - data:
      entity_id: light.porch
    service: light.turn_on
  # temp - for debug
  - data:
      message: "Porch light turned on"
    service: notify.telegram
# Turn on hall light if motion detected and sun is down
- alias: Hall nightlight
  initial_state: on
  trigger:
    platform: state
    entity_id: !secret wyze_motion_hall
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: 'sun.sun'
        state: 'below_horizon'
      - condition: state
        entity_id: 'light.hallway'
        state: 'off'
  action:
  - service: light.turn_on
    data:
      entity_id: light.hallway
      brightness_pct: 20
      transition: 3
  - delay: 00:00:30
  - service: light.turn_off
    data:
      entity_id: light.hallway
      transition: 3
