# Turn bedroom lights on 100% when Flic button single pressed
- alias: Flic bedroom lights on
  trigger:
  - event_data:
      button_name: !secret flic_bedroom
      click_type: single
    event_type: flic_click
    platform: event
  condition: []
  action:
  - data:
      entity_id: light.bedroom
      brightness_pct: 100
    service: light.turn_on
# Turn bedroom lights off when Flic button long pressed
- alias: Flic bedroom lights off
  trigger:
  - event_data:
      button_name: !secret flic_bedroom
      click_type: hold
    event_type: flic_click
    platform: event
  condition: []
  action:
  - data:
      entity_id: light.bedroom
    service: light.turn_off
# Turn bedroom lights down when Flic button double pressed
- alias: Flic bedroom nightlight
  trigger:
  - event_data:
      button_name: !secret flic_bedroom
      click_type: double
    event_type: flic_click
    platform: event
  condition: []
  action:
  - data:
      entity_id: light.desk, light.wall
    service: light.turn_off
  - data:
      entity_id: light.ceiling
      brightness_pct: 1
    service: light.turn_on
