# Telegram chatbot commands
# Help - list commands
- alias: 'Help'
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: '/help'
  action:
    - service: notify.telegram
      data:
        message: 'Available commands are: '
        data:
          keyboard:
            - '/getversion'

# Get Home Assistant version
- alias: 'Get HASS Version'
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: '/getversion'
  action:
    - service: notify.telegram
      data_template:
        message: "Your Home Assistant version is {{ states.sensor.current_version.state }}"
