# Telegram chatbot commands
# Help - list commands
- alias: 'Help'
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: '/help'
  action:
    - service: notify.telegram
      data:
        message: 'Available commands are: '
        data:
          keyboard:
            - '/version, /light'

# Get Home Assistant version
- alias: 'Get HASS Version'
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: '/version'
  action:
    - service: notify.telegram
      data_template:
        message: "Your Home Assistant version is {{ states.sensor.current_version.state }}"

# Set light percent
- alias: 'Set light percent'
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: '/light'
  condition:
    condition: template
    # Check if argument contains percent symbol or is number in valid range
    value_template: >
      {% if ("%" in trigger.event.data["args"][1]) or ((trigger.event.data["args"][1] | int > 0) and (trigger.event.data["args"][1] | int <= 100)) %}
        true
      {% else %}
        false
      {% endif %}
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.{{ trigger.event.data["args"][0] }}
        brightness_pct: >
          {% if '%' in trigger.event.data["args"][1] %}
            {{ trigger.event.data["args"][1].split("%")[0] }}
          {% else %}
            {{ trigger.event.data["args"][1] }}
          {% endif %}
    - service: notify.telegram
      data_template:
        message: 'Setting the {{ trigger.event.data["args"][0] }} lights to {{ trigger.event.data["args"][1] }}!' 

# Toggle light on or off
- alias: 'Set light on off'
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: '/light'
  condition:
    condition: template
    # Check if argument is equal to on or off
    value_template: >
      {% if (trigger.event.data["args"][1] == "on") or (trigger.event.data["args"][1] == "off")  %}
        true
      {% else %}
        false
      {% endif %}
  action:
    - service_template: light.turn_{{ trigger.event.data["args"][1] }}
      data_template:
        entity_id: light.{{ trigger.event.data["args"][0] }}
    - service: notify.telegram
      data_template:
        message: 'Turning the {{ trigger.event.data["args"][0] }} lights {{ trigger.event.data["args"][1] }}!' 
