# Telegram chatbot commands
# Help - list commands
- alias: 'Help'
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: '/help'
  action:
    - service: notify.telegram
      data:
        message: 'Available commands are: '
        data:
          keyboard:
            - '/version, /lights, /lightspct'

# Get Home Assistant version
- alias: 'Get HASS Version'
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: '/version'
  action:
    - service: notify.telegram
      data_template:
        message: "Your Home Assistant version is {{ states.sensor.current_version.state }}"

# Set lights percent
- alias: 'Lights percent'
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: '/lightspct'
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.{{ trigger.event.data["args"][0] }}
        brightness_pct: >
          {% if '%' in trigger.event.data["args"][1] %}
            {{ trigger.event.data["args"][1].split("%")[0] }}
          {% else %}
            {{ trigger.event.data["args"][1] }}
          {% endif %}
    - service: notify.telegram
      data_template:
        message: 'Setting the {{ trigger.event.data["args"][0] }} lights to {{ trigger.event.data["args"][1] }}!' 

# Toggle lights
- alias: 'Set lights'
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: '/lights'
  action:
    - service_template: light.turn_{{ trigger.event.data["args"][1] }}
      data_template:
        entity_id: light.{{ trigger.event.data["args"][0] }}
    - service: notify.telegram
      data_template:
        message: 'Turning the {{ trigger.event.data["args"][0] }} lights {{ trigger.event.data["args"][1] }}!' 
